# Generated by Django 5.2.3 on 2025-06-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_peremption', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturesElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac', to='application.factures')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.produits')),
            ],
        ),
    ]
